name: publica

on: push

jobs:
  incercam-cr:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Login to github container registry
        run: |
          echo $GITHUB_TOKEN | docker login ghcr.io -u duduta --password-stdin
