name: publica

on: push

jobs:
  incercam-cr:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Right now the workflow is executing! :)

      - name: Build the buna-lume Docker image
        run: |
          echo $CONTR_PAT | docker login ghcr.io -u duduta --password-stdin
        env:
          CONTR_PAT: ${{ secrets.CONTR_PAT }}
